### ISSUE TITLE
Issue installing zroya using PIP

### ISSUE THREAD

**Issue by teck968** [malja/zroya#5]
PIP install for this library does not appear to work correctly. 
The install completes successfully, however the library was never actually installed. 

zroya v0.1.0
Python v3.6
PIP v9.0.1
Windows 10.0.16299.309

**Comment by malja** [comment]
Hi, @teck968, thank you for bug report. I will look up this tomorrow.

As far as I know, pypi version is outdated. I did some major changes in source code soon after first upload. Since then, I was testing on my local machine. 
It seems that zroya directory is created in site-packages, but just with bunch of metadata without source code :/

**Comment by malja** [comment]
Pip version is updated to 0.1.2. Check it out.
